version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column

  postgres:
    restart: unless-stopped
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: